name: flutter_vtv
description: "VTV is an E-commerce App using Flutter"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.3-pre

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  # ui
  flutter_svg: ^2.0.9
  flutter_native_splash: ^2.3.9
  google_fonts: ^6.1.0

  # navigation + state management
  go_router: ^13.0.1
  flutter_bloc: ^8.1.3

  # storage
  shared_preferences: ^2.2.2

  # notification
  flutter_local_notifications: ^16.3.1+1

  # functional
  intl: ^0.19.0
  dartz: ^0.10.1
  provider: ^6.1.1
  get_it: ^7.6.7
  injectable: ^2.3.2
  equatable: ^2.0.5
  connectivity_plus: ^5.0.2
  
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  injectable_generator:
  change_app_package_name:
  build_runner:

  flutter_test:
    sdk: flutter

  # activated in the `analysis_options.yaml` file.
  flutter_lints: ^3.0.1

# following page: https://dart.dev/tools/pub/pubspec
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - google_fonts/
    - assets/
    - assets/images/
    - assets/svg/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # see https://flutter.dev/custom-fonts/#from-packages
