// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_vtv/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:convert' as _i17;
import 'dart:typed_data' as _i19;

import 'package:connectivity_plus/connectivity_plus.dart' as _i15;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i16;
import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i4;
import 'package:flutter_vtv/core/error/failures.dart' as _i9;
import 'package:flutter_vtv/core/helpers/secure_storage_helper.dart' as _i14;
import 'package:flutter_vtv/core/network/base_response.dart' as _i3;
import 'package:flutter_vtv/features/auth/data/data_sources/auth_data_source.dart'
    as _i11;
import 'package:flutter_vtv/features/auth/data/models/auth_model.dart' as _i12;
import 'package:flutter_vtv/features/auth/data/models/user_info_model.dart'
    as _i13;
import 'package:flutter_vtv/features/auth/domain/dto/register_params.dart'
    as _i10;
import 'package:flutter_vtv/features/auth/domain/entities/auth_entity.dart'
    as _i5;
import 'package:flutter_vtv/features/auth/domain/repositories/auth_repository.dart'
    as _i7;
import 'package:http/http.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDataResponse_1<T> extends _i1.SmartFake
    implements _i3.DataResponse<T> {
  _FakeDataResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSuccessResponse_2 extends _i1.SmartFake
    implements _i3.SuccessResponse {
  _FakeSuccessResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterSecureStorage_3 extends _i1.SmartFake
    implements _i4.FlutterSecureStorage {
  _FakeFlutterSecureStorage_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthEntity_4 extends _i1.SmartFake implements _i5.AuthEntity {
  _FakeAuthEntity_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_5 extends _i1.SmartFake implements _i6.Response {
  _FakeResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_6 extends _i1.SmartFake
    implements _i6.StreamedResponse {
  _FakeStreamedResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i7.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i9.Failure, _i5.AuthEntity>> retrieveAuth() =>
      (super.noSuchMethod(
        Invocation.method(
          #retrieveAuth,
          [],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, _i5.AuthEntity>>.value(
            _FakeEither_0<_i9.Failure, _i5.AuthEntity>(
          this,
          Invocation.method(
            #retrieveAuth,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, _i5.AuthEntity>>);

  @override
  _i8.Future<_i2.Either<_i3.ErrorResponse, _i3.DataResponse<_i5.AuthEntity>>>
      loginWithUsernameAndPassword(
    String? username,
    String? password,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #loginWithUsernameAndPassword,
              [
                username,
                password,
              ],
            ),
            returnValue: _i8.Future<
                _i2.Either<_i3.ErrorResponse,
                    _i3.DataResponse<_i5.AuthEntity>>>.value(_FakeEither_0<
                _i3.ErrorResponse, _i3.DataResponse<_i5.AuthEntity>>(
              this,
              Invocation.method(
                #loginWithUsernameAndPassword,
                [
                  username,
                  password,
                ],
              ),
            )),
          ) as _i8.Future<
              _i2.Either<_i3.ErrorResponse, _i3.DataResponse<_i5.AuthEntity>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, void>> cacheAuth(
          _i5.AuthEntity? authEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheAuth,
          [authEntity],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, void>>.value(
            _FakeEither_0<_i9.Failure, void>(
          this,
          Invocation.method(
            #cacheAuth,
            [authEntity],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, void>>);

  @override
  _i8.Future<_i2.Either<_i3.ErrorResponse, _i3.SuccessResponse>> logout(
          String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #logout,
          [refreshToken],
        ),
        returnValue: _i8
            .Future<_i2.Either<_i3.ErrorResponse, _i3.SuccessResponse>>.value(
            _FakeEither_0<_i3.ErrorResponse, _i3.SuccessResponse>(
          this,
          Invocation.method(
            #logout,
            [refreshToken],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i3.ErrorResponse, _i3.SuccessResponse>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, void>> deleteAuth() => (super.noSuchMethod(
        Invocation.method(
          #deleteAuth,
          [],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, void>>.value(
            _FakeEither_0<_i9.Failure, void>(
          this,
          Invocation.method(
            #deleteAuth,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, void>>);

  @override
  _i8.Future<_i2.Either<_i3.ErrorResponse, _i3.SuccessResponse>> register(
          _i10.RegisterParams? registerParams) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [registerParams],
        ),
        returnValue: _i8
            .Future<_i2.Either<_i3.ErrorResponse, _i3.SuccessResponse>>.value(
            _FakeEither_0<_i3.ErrorResponse, _i3.SuccessResponse>(
          this,
          Invocation.method(
            #register,
            [registerParams],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i3.ErrorResponse, _i3.SuccessResponse>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, bool>> isExpiredToken(
          String? accessToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #isExpiredToken,
          [accessToken],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, bool>>.value(
            _FakeEither_0<_i9.Failure, bool>(
          this,
          Invocation.method(
            #isExpiredToken,
            [accessToken],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, bool>>);

  @override
  _i8.Future<_i2.Either<_i3.ErrorResponse, _i3.DataResponse<String>>>
      getNewAccessToken() => (super.noSuchMethod(
            Invocation.method(
              #getNewAccessToken,
              [],
            ),
            returnValue: _i8.Future<
                    _i2
                    .Either<_i3.ErrorResponse, _i3.DataResponse<String>>>.value(
                _FakeEither_0<_i3.ErrorResponse, _i3.DataResponse<String>>(
              this,
              Invocation.method(
                #getNewAccessToken,
                [],
              ),
            )),
          ) as _i8
              .Future<_i2.Either<_i3.ErrorResponse, _i3.DataResponse<String>>>);

  @override
  _i8.Future<_i2.Either<_i3.ErrorResponse, _i3.SuccessResponse>> sendCode(
          String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendCode,
          [username],
        ),
        returnValue: _i8
            .Future<_i2.Either<_i3.ErrorResponse, _i3.SuccessResponse>>.value(
            _FakeEither_0<_i3.ErrorResponse, _i3.SuccessResponse>(
          this,
          Invocation.method(
            #sendCode,
            [username],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i3.ErrorResponse, _i3.SuccessResponse>>);
}

/// A class which mocks [AuthDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthDataSource extends _i1.Mock implements _i11.AuthDataSource {
  MockAuthDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i3.DataResponse<_i12.AuthModel>> loginWithUsernameAndPassword(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithUsernameAndPassword,
          [
            username,
            password,
          ],
        ),
        returnValue: _i8.Future<_i3.DataResponse<_i12.AuthModel>>.value(
            _FakeDataResponse_1<_i12.AuthModel>(
          this,
          Invocation.method(
            #loginWithUsernameAndPassword,
            [
              username,
              password,
            ],
          ),
        )),
      ) as _i8.Future<_i3.DataResponse<_i12.AuthModel>>);

  @override
  _i8.Future<_i3.SuccessResponse> register(_i10.RegisterParams? registerDTO) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [registerDTO],
        ),
        returnValue:
            _i8.Future<_i3.SuccessResponse>.value(_FakeSuccessResponse_2(
          this,
          Invocation.method(
            #register,
            [registerDTO],
          ),
        )),
      ) as _i8.Future<_i3.SuccessResponse>);

  @override
  _i8.Future<_i3.SuccessResponse> revokeRefreshToken(String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #revokeRefreshToken,
          [refreshToken],
        ),
        returnValue:
            _i8.Future<_i3.SuccessResponse>.value(_FakeSuccessResponse_2(
          this,
          Invocation.method(
            #revokeRefreshToken,
            [refreshToken],
          ),
        )),
      ) as _i8.Future<_i3.SuccessResponse>);

  @override
  _i8.Future<_i3.DataResponse<String>> getNewAccessToken(
          String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNewAccessToken,
          [refreshToken],
        ),
        returnValue: _i8.Future<_i3.DataResponse<String>>.value(
            _FakeDataResponse_1<String>(
          this,
          Invocation.method(
            #getNewAccessToken,
            [refreshToken],
          ),
        )),
      ) as _i8.Future<_i3.DataResponse<String>>);

  @override
  _i8.Future<_i3.DataResponse<_i12.AuthModel>> getUserProfile(
          {required String? accessToken}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
          {#accessToken: accessToken},
        ),
        returnValue: _i8.Future<_i3.DataResponse<_i12.AuthModel>>.value(
            _FakeDataResponse_1<_i12.AuthModel>(
          this,
          Invocation.method(
            #getUserProfile,
            [],
            {#accessToken: accessToken},
          ),
        )),
      ) as _i8.Future<_i3.DataResponse<_i12.AuthModel>>);

  @override
  _i8.Future<_i3.SuccessResponse> editUserProfile({
    required String? accessToken,
    required _i13.UserInfoModel? newInfo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #editUserProfile,
          [],
          {
            #accessToken: accessToken,
            #newInfo: newInfo,
          },
        ),
        returnValue:
            _i8.Future<_i3.SuccessResponse>.value(_FakeSuccessResponse_2(
          this,
          Invocation.method(
            #editUserProfile,
            [],
            {
              #accessToken: accessToken,
              #newInfo: newInfo,
            },
          ),
        )),
      ) as _i8.Future<_i3.SuccessResponse>);

  @override
  _i8.Future<_i3.SuccessResponse> requestOtpForResetPassword(
          String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestOtpForResetPassword,
          [username],
        ),
        returnValue:
            _i8.Future<_i3.SuccessResponse>.value(_FakeSuccessResponse_2(
          this,
          Invocation.method(
            #requestOtpForResetPassword,
            [username],
          ),
        )),
      ) as _i8.Future<_i3.SuccessResponse>);

  @override
  _i8.Future<_i3.SuccessResponse> resetPassword({
    required String? username,
    required String? otp,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [],
          {
            #username: username,
            #otp: otp,
            #newPassword: newPassword,
          },
        ),
        returnValue:
            _i8.Future<_i3.SuccessResponse>.value(_FakeSuccessResponse_2(
          this,
          Invocation.method(
            #resetPassword,
            [],
            {
              #username: username,
              #otp: otp,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i8.Future<_i3.SuccessResponse>);

  @override
  _i8.Future<_i3.SuccessResponse> changePassword({
    required String? username,
    required String? oldPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [],
          {
            #username: username,
            #oldPassword: oldPassword,
            #newPassword: newPassword,
          },
        ),
        returnValue:
            _i8.Future<_i3.SuccessResponse>.value(_FakeSuccessResponse_2(
          this,
          Invocation.method(
            #changePassword,
            [],
            {
              #username: username,
              #oldPassword: oldPassword,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i8.Future<_i3.SuccessResponse>);
}

/// A class which mocks [SecureStorageHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageHelper extends _i1.Mock
    implements _i14.SecureStorageHelper {
  MockSecureStorageHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FlutterSecureStorage get I => (super.noSuchMethod(
        Invocation.getter(#I),
        returnValue: _FakeFlutterSecureStorage_3(
          this,
          Invocation.getter(#I),
        ),
      ) as _i4.FlutterSecureStorage);

  @override
  _i8.Future<bool> get isLogin => (super.noSuchMethod(
        Invocation.getter(#isLogin),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i5.AuthEntity> readAuth() => (super.noSuchMethod(
        Invocation.method(
          #readAuth,
          [],
        ),
        returnValue: _i8.Future<_i5.AuthEntity>.value(_FakeAuthEntity_4(
          this,
          Invocation.method(
            #readAuth,
            [],
          ),
        )),
      ) as _i8.Future<_i5.AuthEntity>);

  @override
  _i8.Future<void> cacheAuth(String? jsonData) => (super.noSuchMethod(
        Invocation.method(
          #cacheAuth,
          [jsonData],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteAuth() => (super.noSuchMethod(
        Invocation.method(
          #deleteAuth,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteAll() => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i15.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<_i16.ConnectivityResult> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i8.Stream<_i16.ConnectivityResult>.empty(),
      ) as _i8.Stream<_i16.ConnectivityResult>);

  @override
  _i8.Future<_i16.ConnectivityResult> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i8.Future<_i16.ConnectivityResult>.value(
            _i16.ConnectivityResult.bluetooth),
      ) as _i8.Future<_i16.ConnectivityResult>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i6.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i8.Future<_i6.Response>);

  @override
  _i8.Future<_i6.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i8.Future<_i6.Response>);

  @override
  _i8.Future<_i6.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i17.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response>);

  @override
  _i8.Future<_i6.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i17.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response>);

  @override
  _i8.Future<_i6.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i17.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response>);

  @override
  _i8.Future<_i6.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i17.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response>);

  @override
  _i8.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<String>.value(_i18.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i19.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<_i19.Uint8List>.value(_i19.Uint8List(0)),
      ) as _i8.Future<_i19.Uint8List>);

  @override
  _i8.Future<_i6.StreamedResponse> send(_i6.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i8.Future<_i6.StreamedResponse>.value(_FakeStreamedResponse_6(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i8.Future<_i6.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
